### ISSUE TITLE
Explain Gradle configuration

### ISSUE THREAD

**Issue by gajwani** [berlin-ab/spring-kotlin-demo#6]
I was looking around the repository, and it's using some interesting Gradle configuration to accomplish the separation of domain concepts into packages.

Could you either put in another Markdown file, or use a section of the README to explain some Gradle best practices to accomplish this? It's difficult to Google, but I really want to replicate this in our project.

Thanks!

**Comment by berlin-ab** [comment]
I'll drop a note in the README.

**Comment by berlin-ab** [comment]
@gajwani Let me know if I can clarify it further.
